blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail')
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('experience/', include('experience.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

experience/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'experience'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail')
]

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

experience/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='experience/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField, DateField
from django.db.models.fields.files import ImageField
import datetime



class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)
    
class Icon(models.Model):
    image = ImageField(upload_to='portfolio/images/')
    title = CharField(max_length=50, default='Sin título')
    
class Education(models.Model):
    image = ImageField(upload_to='portfolio/images/')
    title = CharField(max_length=50)
    description = CharField(max_length=150)
    date_ini = DateField(default=datetime.date.today, null=True, blank=True)
    date_fin = DateField(default=datetime.date.today, null=True, blank=True)
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    msj = models.TextField(default='Hola, Maribel, vi tu portafolio y deseo contactarme contigo')

    def __str__(self):
        return self.name

experience/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    total_posts = Post.objects.count()
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post, 'total_posts': total_posts})

portfolio/views.py
from django.shortcuts import render
from .models import Project, Icon, Education, Contact

def home(request):
    projects = Project.objects.all()
    icons = Icon.objects.all()
    educations = Education.objects.all()
    context = {
        'projects': projects,
        'icons': icons,
        'educations':educations
    }
    return render(request, 'home.html', context)

def contact_view(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    return render(request, 'home.html', {'phone': contact.phone, 'msg': contact.msj})

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content%}

<h1 class="fs-2">Mi experiecia<h1>
    <h3>Experiencia laboral y educativa {{total_posts}} {{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3 card-exp">
    <div class="card card-body">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description | truncatechars:100 }}</p>
                <p>{{post.date |date:'M d Y' |upper}}</p>
                <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock%}

experience/templates/post_detail.html
{% extends 'layout.html' %}

{% block content%}

<div class="text-center card-detail bg-grey">
    <h1>{{post.title}}</h1>
    <h2 class="my-2 h5">{{post.date|date:'F jS Y'}}</h2>
    <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
    <div class="my-4 py-2">
        <p>{{post.description}}</p>
    </div>
</div>

{% endblock%}

experience/templates/posts.html
{% extends 'layout.html' %}

{% block content%}

<h1 class="fs-2">Mi experiecia<h1>
    <h3>Experiencia laboral y educativa {{total_posts}} {{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3 card-exp">
    <div class="card card-body">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description | truncatechars:100 }}</p>
                <p>{{post.date |date:'M d Y' |upper}}</p>
                <a href="{% url 'experience:post_detail' post.id %}">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock%}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}


<header class="row bg-grey pst-card">
    <div class="col-md-4 image-container">
        <img
            class="custom-img custom-img-filter"
            src="{% static 'foto2.png' %}"
            alt=""
        />
    </div>
    <div class="col-md-8 my-auto p-4 text-center">
        <h1><strong>Maribel Alejandra Pilquinao</strong></h1>
        <h3>Developer full Stack</h3>
        <p>
            Profesional de la tecnología con una sólida combinación de
            habilidades técnicas y de gestión. Experiencia en el diseño e
            implementación de soluciones de seguridad de la información,
            garantizando la protección de los activos digitales de la
            organización. Conocimientos en desarrollo de software y experiencia
            en el seguimiento de proyectos y en la elaboración de procedimientos
            operativos estándar.
        </p>
        <a
            class="btn btn-light btn-lg rounded-1 my-3"
            href="{% static 'cv.pdf' %}"
            target="_blank"
            >Descargar CV</a
        >
        <a
            href="https://www.linkedin.com/in/maribel-pilquinao/"
            target="_blank"
            ><img
                class="img-linkedin"
                src="{% static 'link.png' %}"
                alt=""
        /></a>
    </div>
</header>
<!-- conocimientos tecnicos -->
<div id="iconCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="text-center p-4 my-4">
        <h3>Conocimientos técnicos</h3>
    </div>
    <div class="carousel-inner">
        {% for icon in icons %}
        {% if forloop.counter0|divisibleby:3 %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="row justify-content-center">
        {% endif %}

        <div class="col-4 text-center">
            <img class="icon d-block mx-auto" src="{{ icon.image.url }}" alt="Icon {{ forloop.counter }}">
            <h4>{{icon.title}}</h4>
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="p-4 my-4">
        <button class="carousel-control-prev" type="button" data-bs-target="#iconCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#iconCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<!-- Sección del portafolio -->
<div class="row my-4 text-center">
    <h3>Mis proyectos</h3>

    {% for project in projects %}
    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img
                src="{{ project.image.url }}"
                alt=""
            />
            <div class="card-body">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>

                {% if project.url %}
                <a href="{{ project.url }}" target="_blank">Ir al proyecto</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- educacion -->

<div class="row my-4 text-center justify-content-center">
    <h4 class="mb-4">Educación</h4>
    {% for education in educations %}
    <div class="col-md-6 col-lg-3">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <img class="card-img-top mx-auto d-block img-education" src="{{ education.image.url }}" alt="">
          <h5 class="card-title">{{ education.title }}</h5>
          <p class="card-text">{{ education.description }}</p>
          <p class="card-text">
            <small class="text-muted">
              {{ education.date_ini |date:'M d Y'}} - {{ education.date_fin |date:'M d Y'}}
            </small>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

<div class="container-contact row" >
    <div class="contact">
        <a href="https://wa.me/51922455621?text=Hola,%20Maribel" target="_blank"><img src="{% static 'whatsapp.png' %}" alt=""></a>
    </div>
    <div class="contact">
        <a href="mailto:maribel.pilquinaopm@gmailcom?subject=Consulta&body=Hola,%20me%20gustaría%20más%20información" target="_blank"><img class="btn" src="{% static 'gmail.png' %}" alt=""></a>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">

</head>
<body class="text-light body-bg ">
    {% include 'partials/navbar.html' %}
    
    <div class="container p-4 wrapper">
        {% block content%}
        {% endblock%}
    </div>
    <div class="container-contact row" >
        <div class="contact">
            <a href="https://wa.me/51922455621?text=Hola,%20Maribel" target="_blank"><img src="{% static 'whatsapp.png' %}" alt=""></a>
        </div>
        <div class="contact">
            <a href="mailto:maribel.pilquinaopm@gmailcom?subject=Consulta&body=Hola,%20me%20gustaría%20más%20información" target="_blank"><img class="btn" src="{% static 'gmail.png' %}" alt=""></a>
        </div>
    </div>

    {% include 'partials/footer.html'%}
</body>
</html>

portfolio/templates/partials/footer.html
{% load static %}

<footer>
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">Contáctame</h5>
            <div class="d-flex justify-content-center">
                <div>
                    <a
                        href="https://www.linkedin.com/in/maribel-pilquinao/"
                        target="_blank"
                        ><img
                            class="icon-rrss"
                            src="{% static 'link.png'%}"
                            alt=""
                    /></a>
                </div>
                <div>
                    <a
                        href="https://x.com/Maribel_alej"
                        target="_blank"
                        ><img
                            class="icon-rrss"
                            src="{% static 'x.png'%}"
                            alt=""
                    /></a>
                </div>
                <div>
                    <a
                        href="https://www.instagram.com/maribelalejandrap/"
                        target="_blank"
                        ><img
                            class="icon-rrss"
                            src="{% static 'instagram.png'%}"
                            alt=""
                    /></a>
                </div>
                <div>
                    <a
                        href="https://github.com/MaribelPilquinao"
                        target="_blank"
                        ><img
                            class="icon-rrss"
                            src="{% static 'github.png'%}"
                            alt=""
                    /></a>
                </div>
            </div>
        </div>
        <div class="card-footer text-body-secondary">By Maribel Pilquinao</div>
    </div>
</footer>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a
            class="custom-phrase"
            class="navbar-brand"
            href="/"
            >"La innovacion distingue a un lider de un seguidor."</a
        >
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div
            class="collapse navbar-collapse"
            id="navbarNav"
        >
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a
                        class="nav-link"
                        href="{% url 'experience:posts'%}"
                        >Experiencia</a
                    >
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a
                        class="btn btn-primary btn-sm"
                        href="{% static 'cv.pdf' %}"
                        target="_blank"
                        >Descargar CV</a
                    >
                </li>
            </ul>
        </div>
    </div>
</nav>